// GENERATED by tools/packRoads.mjs — do not edit.
// Run `npm run pack-roads` to regenerate (requires TempArt/).
//
// Art: Aleksandr Makarov (@IknowKingRabbit). See ART-CREDITS.md.
//
// The sheet is shipped as the artist drew it: 4 road materials, each an
// 8x5 block of 16px tiles, plus 4 bridge tiles on the bottom row.
// What is generated here is the part the art does not carry — which tile to
// place for which neighbourhood.

export const ROAD_TILE = 16
export const ROAD_SHEET_WIDTH = 256
export const ROAD_SHEET_HEIGHT = 176

/** Tiles across and down one material's block. */
export const ROAD_BLOCK_W = 8
export const ROAD_BLOCK_H = 5

export const ROAD_MATERIALS = ['dirt', 'gravel', 'cobble', 'brick'] as const
export type RoadMaterial = (typeof ROAD_MATERIALS)[number]

/**
 * Where each material's block starts, in tiles from the sheet's top left.
 *
 * All 4 blocks are the same layout — the packer verifies it and refuses to
 * emit if they ever diverge — so a material is only ever an offset.
 */
export const ROAD_BLOCK_ORIGIN: readonly (readonly [number, number])[] = [
  [0, 0], // dirt, fill rgb(244,210,156)
  [8, 0], // gravel, fill rgb(165,141,107)
  [0, 5], // cobble, fill rgb(147,154,180)
  [8, 5], // brick, fill rgb(243,221,172)
]

/** Bridge tiles, in tiles from the sheet's top left. Placed by hand, not autotiled. */
export const ROAD_BRIDGES: Readonly<Record<string, readonly [number, number]>> = {
  stoneWide: [12, 10],
  stoneNarrow: [13, 10],
  plankWide: [14, 10],
  plankNarrow: [15, 10],
}

/**
 * Tile to draw for each of the 256 neighbourhoods, as (tx, ty) pairs *within* a
 * material's block. Index is the 8-way mask, clockwise from north:
 *
 *   N=1  NE=2  E=4  SE=8  S=16  SW=32  W=64  NW=128
 *
 * Every entry is filled, so a lookup can never miss. Set a bit for each of the
 * eight neighbours that is also road, index this, add the material's origin.
 * No normalisation is needed at the call site — corners that cannot apply are
 * already folded out here.
 *
 * The sheet draws 38 tiles covering 33 of the 47 canonical blob
 * neighbourhoods. The remaining 14 resolve to their nearest drawn neighbour,
 * counting an edge mismatch as four times a corner mismatch — a wrong edge
 * leaves a visible gap in the road, a wrong corner only rounds a join.
 *
 * Approximated masks: 23, 29, 71, 87, 92, 93, 113, 116, 117, 119, 197, 209, 213, 221.
 */
export const ROAD_TILE_FOR_MASK: readonly (readonly [number, number])[] = [
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [1, 1], [1, 2], [1, 1], [1, 2], [3, 1], [0, 2], [3, 1], [5, 1],
  [1, 1], [1, 2], [1, 1], [1, 2], [5, 0], [5, 1], [5, 0], [5, 1],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [1, 1], [1, 2], [1, 1], [1, 2], [3, 1], [0, 2], [3, 1], [5, 1],
  [1, 1], [1, 2], [1, 1], [1, 2], [5, 0], [5, 1], [5, 0], [5, 1],
  [4, 0], [4, 2], [4, 0], [4, 2], [3, 0], [2, 1], [3, 0], [6, 2],
  [4, 0], [4, 2], [4, 0], [4, 2], [3, 0], [2, 1], [3, 0], [6, 2],
  [4, 1], [0, 3], [4, 1], [0, 3], [2, 2], [0, 1], [2, 2], [4, 3],
  [4, 1], [0, 3], [4, 1], [0, 3], [6, 0], [4, 3], [6, 0], [4, 3],
  [4, 0], [4, 2], [4, 0], [4, 2], [3, 0], [2, 1], [3, 0], [6, 2],
  [4, 0], [4, 2], [4, 0], [4, 2], [3, 0], [2, 1], [3, 0], [6, 2],
  [7, 0], [7, 1], [7, 0], [7, 1], [6, 0], [5, 3], [6, 0], [6, 3],
  [7, 0], [7, 1], [7, 0], [7, 1], [6, 0], [4, 4], [6, 0], [6, 3],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [1, 1], [1, 2], [1, 1], [1, 2], [3, 1], [0, 2], [3, 1], [5, 1],
  [1, 1], [1, 2], [1, 1], [1, 2], [5, 0], [5, 1], [5, 0], [5, 1],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [0, 4], [1, 3], [0, 4], [1, 3], [2, 0], [3, 2], [2, 0], [5, 2],
  [1, 1], [1, 2], [1, 1], [1, 2], [3, 1], [0, 2], [3, 1], [5, 1],
  [1, 1], [1, 2], [1, 1], [1, 2], [5, 0], [5, 1], [5, 0], [5, 1],
  [4, 0], [7, 2], [4, 0], [7, 2], [3, 0], [6, 2], [3, 0], [6, 2],
  [4, 0], [7, 2], [4, 0], [7, 2], [3, 0], [6, 2], [3, 0], [6, 2],
  [4, 1], [7, 1], [4, 1], [7, 1], [2, 2], [5, 3], [2, 2], [5, 4],
  [4, 1], [7, 1], [4, 1], [7, 1], [6, 0], [7, 3], [6, 0], [6, 4],
  [4, 0], [7, 2], [4, 0], [7, 2], [3, 0], [6, 2], [3, 0], [6, 2],
  [4, 0], [7, 2], [4, 0], [7, 2], [3, 0], [6, 2], [3, 0], [6, 2],
  [7, 0], [7, 1], [7, 0], [7, 1], [6, 0], [5, 3], [6, 0], [7, 4],
  [7, 0], [7, 1], [7, 0], [7, 1], [6, 0], [7, 3], [6, 0], [6, 1],
]
