// GENERATED by tools/packSprites.mjs — do not edit.
// Run `npm run pack-sprites` to regenerate (requires TempArt/).
//
// Art: Aleksandr Makarov (@IknowKingRabbit). See ART-CREDITS.md.

export const ATLAS_WIDTH = 256
export const ATLAS_HEIGHT = 2048

export interface SpriteFrame {
  /** Pixel rect within the atlas. */
  x: number
  y: number
  w: number
  h: number
  /** Present on animation sheets: the frame grid within the rect. */
  cols?: number
  rows?: number
}

export const SPRITE_FRAMES = {
  'unit.castle.peasant': { x: 138, y: 502, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.pikeman': { x: 2, y: 602, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.archer': { x: 70, y: 602, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.swordsman': { x: 138, y: 602, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.monk': { x: 2, y: 686, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.cavalier': { x: 70, y: 686, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.griffin': { x: 138, y: 686, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.paladin': { x: 2, y: 770, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.castle.angel': { x: 70, y: 770, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.necropolis.skeleton': { x: 138, y: 770, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.necropolis.zombie': { x: 2, y: 854, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.necropolis.ghost': { x: 70, y: 854, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.necropolis.spider': { x: 138, y: 854, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.necropolis.vampire': { x: 2, y: 2, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.necropolis.lich': { x: 70, y: 2, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.necropolis.death_knight': { x: 2, y: 938, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.imp': { x: 70, y: 938, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.gog': { x: 138, y: 938, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.hell_hound': { x: 2, y: 1022, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.demon': { x: 70, y: 1022, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.pit_fiend': { x: 138, y: 1022, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.efreet': { x: 2, y: 1106, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.darkBastion.devil': { x: 138, y: 2, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.stronghold.goblin': { x: 70, y: 1106, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.stronghold.wolf_rider': { x: 138, y: 1106, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.stronghold.centaur': { x: 2, y: 1190, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.stronghold.harpy': { x: 70, y: 1190, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.stronghold.shaman': { x: 2, y: 102, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.stronghold.troll': { x: 138, y: 1190, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.stronghold.cyclop': { x: 2, y: 1274, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.gremlin': { x: 70, y: 102, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.wizards.gargoyle': { x: 70, y: 1274, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.golem': { x: 138, y: 1274, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.djinn': { x: 2, y: 1358, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.naga': { x: 70, y: 1358, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.lion': { x: 138, y: 1358, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.wizards.titan': { x: 2, y: 1442, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.pixie': { x: 70, y: 1442, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.deer': { x: 138, y: 1442, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.dwarf': { x: 2, y: 1526, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.hunter': { x: 70, y: 1526, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.druid': { x: 138, y: 102, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.greatElf.satyr': { x: 138, y: 1526, w: 64, h: 80, cols: 4, rows: 5 },
  'unit.greatElf.treant': { x: 2, y: 202, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.stone_elemental': { x: 70, y: 202, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.ice_elemental': { x: 138, y: 202, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.fire_elemental': { x: 2, y: 302, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.water_elemental': { x: 70, y: 302, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.wind_elemental': { x: 138, y: 302, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.magma_elemental': { x: 2, y: 402, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.storm_elemental': { x: 70, y: 402, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.mind_elemental': { x: 138, y: 402, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.magic_elemental': { x: 2, y: 502, w: 64, h: 96, cols: 4, rows: 6 },
  'unit.elementals.diamond_elemental': { x: 70, y: 502, w: 64, h: 96, cols: 4, rows: 6 },
} as const satisfies Record<string, SpriteFrame>

export type SpriteKey = keyof typeof SPRITE_FRAMES

/** What a sprite *is*, derived from its key prefix by the packer. */
export type SpriteRole = 'unit'

export interface SpriteTags {
  role: SpriteRole
  /**
   * Biome ids whose palette this sprite suits. Absent means it suits any —
   * either because it is palette-neutral, or because its key already carries
   * the biome's ground sheet and callers build the key rather than search for it.
   */
  biomes?: readonly string[]
}

export const SPRITE_TAGS = {
  'unit.castle.peasant': { role: 'unit' },
  'unit.castle.pikeman': { role: 'unit' },
  'unit.castle.archer': { role: 'unit' },
  'unit.castle.swordsman': { role: 'unit' },
  'unit.castle.monk': { role: 'unit' },
  'unit.castle.cavalier': { role: 'unit' },
  'unit.castle.griffin': { role: 'unit' },
  'unit.castle.paladin': { role: 'unit' },
  'unit.castle.angel': { role: 'unit' },
  'unit.necropolis.skeleton': { role: 'unit' },
  'unit.necropolis.zombie': { role: 'unit' },
  'unit.necropolis.ghost': { role: 'unit' },
  'unit.necropolis.spider': { role: 'unit' },
  'unit.necropolis.vampire': { role: 'unit' },
  'unit.necropolis.lich': { role: 'unit' },
  'unit.necropolis.death_knight': { role: 'unit' },
  'unit.darkBastion.imp': { role: 'unit' },
  'unit.darkBastion.gog': { role: 'unit' },
  'unit.darkBastion.hell_hound': { role: 'unit' },
  'unit.darkBastion.demon': { role: 'unit' },
  'unit.darkBastion.pit_fiend': { role: 'unit' },
  'unit.darkBastion.efreet': { role: 'unit' },
  'unit.darkBastion.devil': { role: 'unit' },
  'unit.stronghold.goblin': { role: 'unit' },
  'unit.stronghold.wolf_rider': { role: 'unit' },
  'unit.stronghold.centaur': { role: 'unit' },
  'unit.stronghold.harpy': { role: 'unit' },
  'unit.stronghold.shaman': { role: 'unit' },
  'unit.stronghold.troll': { role: 'unit' },
  'unit.stronghold.cyclop': { role: 'unit' },
  'unit.wizards.gremlin': { role: 'unit' },
  'unit.wizards.gargoyle': { role: 'unit' },
  'unit.wizards.golem': { role: 'unit' },
  'unit.wizards.djinn': { role: 'unit' },
  'unit.wizards.naga': { role: 'unit' },
  'unit.wizards.lion': { role: 'unit' },
  'unit.wizards.titan': { role: 'unit' },
  'unit.greatElf.pixie': { role: 'unit' },
  'unit.greatElf.deer': { role: 'unit' },
  'unit.greatElf.dwarf': { role: 'unit' },
  'unit.greatElf.hunter': { role: 'unit' },
  'unit.greatElf.druid': { role: 'unit' },
  'unit.greatElf.satyr': { role: 'unit' },
  'unit.greatElf.treant': { role: 'unit' },
  'unit.elementals.stone_elemental': { role: 'unit' },
  'unit.elementals.ice_elemental': { role: 'unit' },
  'unit.elementals.fire_elemental': { role: 'unit' },
  'unit.elementals.water_elemental': { role: 'unit' },
  'unit.elementals.wind_elemental': { role: 'unit' },
  'unit.elementals.magma_elemental': { role: 'unit' },
  'unit.elementals.storm_elemental': { role: 'unit' },
  'unit.elementals.mind_elemental': { role: 'unit' },
  'unit.elementals.magic_elemental': { role: 'unit' },
  'unit.elementals.diamond_elemental': { role: 'unit' },
} as const satisfies Record<SpriteKey, SpriteTags>

const ALL_KEYS = Object.keys(SPRITE_TAGS) as SpriteKey[]

/**
 * Every sprite of a role, in manifest order, optionally narrowed to those whose
 * palette suits a biome.
 *
 * This is what lets placement code ask for "a settlement building that suits the
 * Blight" instead of naming files. Manifest order is stable, so a caller that
 * indexes this with a seeded random draws the same sprite on every run — but it
 * shifts when art is added, which is the same contract the biome prop lists
 * already have.
 */
export function spritesWithRole(role: SpriteRole, biome?: string): SpriteKey[] {
  return ALL_KEYS.filter((key) => {
    const tag: SpriteTags = SPRITE_TAGS[key]
    if (tag.role !== role) return false
    return !biome || !tag.biomes || tag.biomes.includes(biome)
  })
}
